apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQVNLNU1DWUZMSkFVRU1YVUgK
  AWS_SECRET_ACCESS_KEY: ZzRtWURnNytoNXNvMGp0YmtUWDNpMndKWjZ2cFk4QTkvamxyRFFuNAo=
  AWS_DEFAULT_REGION: dXMtZWFzdC0xCg==
